async function call(fn, opts){ const res = await fetch('/.netlify/functions/'+fn, opts); if(!res.ok) throw new Error('HTTP '+res.status); return res.json(); }

function el(tag, props={}, ...children){ const e=document.createElement(tag); for(const k in props){ if(k.startsWith('on')) e.addEventListener(k.substring(2), props[k]); else if(k==='html') e.innerHTML=props[k]; else e.setAttribute(k,props[k]); } for(const c of children) if(typeof c==='string') e.appendChild(document.createTextNode(c)); else if(c) e.appendChild(c); return e; }

function formatCurrency(x){ return Number(x||0).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2})+' Dhs'; }

async function renderStock(){ const main=document.getElementById('main'); main.innerHTML=''; main.appendChild(el('h2',{},'Stock')); try{ const stock = await call('getStock'); const total = stock.reduce((a,r)=>a + Number(r.pu||0)*Number(r.stock||0),0); main.appendChild(el('div',{class:'card'}, el('strong',{},'Valeur totale stock: '), ' ', formatCurrency(total) )); const table=el('table',{class:'table'}); table.appendChild(el('thead',{}, el('tr',{}, el('th',{},'ID'), el('th',{},'Article'), el('th',{},'PU'), el('th',{},'Stock') ))); const tbody=document.createElement('tbody'); stock.forEach(s=>{ tbody.appendChild(el('tr',{}, el('td',{},s.id), el('td',{},s.name), el('td',{},s.pu), el('td',{},s.stock))); }); table.appendChild(tbody); main.appendChild(table); renderSaleForm(stock); }catch(err){ main.appendChild(el('div',{},'Erreur: '+err.message)); } }

function renderSaleForm(stock){ const main=document.getElementById('main'); const card=el('div',{class:'card'}); card.appendChild(el('h3',{},'Déclarer une vente')); const form=el('form',{}); form.appendChild(el('div',{class:'form-row'}, el('label',{},'Type: '), el('select',{name:'type'}, el('option',{value:'lub'},'Lubrifiant'), el('option',{value:'autre'},'Autre')) )); const sel = el('select',{name:'articleId'}); sel.appendChild(el('option',{value:''},'-- choisir --')); stock.forEach(s=> sel.appendChild(el('option',{value:s.id}, s.id+' - '+s.name+' ('+s.stock+')'))); form.appendChild(el('div',{class:'form-row'}, el('label',{},'Article: '), sel)); form.appendChild(el('div',{class:'form-row'}, el('label',{},'Nom article: '), el('input',{name:'articleName'}))); form.appendChild(el('div',{class:'form-row'}, el('label',{},'Client: '), el('input',{name:'client'}))); form.appendChild(el('div',{class:'form-row'}, el('label',{},'Quantité: '), el('input',{name:'qty',type:'number',value:1}))); form.appendChild(el('div',{class:'form-row'}, el('label',{},'PU: '), el('input',{name:'pu',type:'number',value:0}))); form.appendChild(el('div',{class:'form-row'}, el('label',{},'Date: '), el('input',{name:'date',type:'date'}))); const msg=el('div',{}); form.appendChild(el('div',{class:'form-row'}, el('button',{type:'submit'},'Valider'))); form.addEventListener('submit', async (ev)=>{ ev.preventDefault(); const fd=new FormData(form); const body=Object.fromEntries(fd.entries()); try{ const res=await call('createSale',{ method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify(body) }); msg.textContent = 'OK: ' + JSON.stringify(res); await renderStock(); }catch(e){ msg.textContent = 'Erreur: '+e.message; } }); card.appendChild(form); card.appendChild(msg); main.appendChild(card); }

async function renderSales(){ const main=document.getElementById('main'); main.innerHTML=''; main.appendChild(el('h2',{},'Ventes')); try{ const sales = await call('getSales'); const table=el('table',{class:'table'}); table.appendChild(el('thead',{}, el('tr',{}, el('th',{},'Date'), el('th',{},'Type'), el('th',{},'Article'), el('th',{},'Client'), el('th',{},'Qty'), el('th',{},'PU'), el('th',{},'Montant') ))); const tbody=document.createElement('tbody'); sales.forEach(s=> tbody.appendChild(el('tr',{}, el('td',{},s.date||''), el('td',{},s.type), el('td',{},s.article_name||s.articleName||s.article_id), el('td',{},s.client), el('td',{},s.qty), el('td',{},s.pu), el('td',{},s.montant) ))); table.appendChild(tbody); main.appendChild(table); }catch(err){ main.appendChild(el('div',{},'Erreur: '+err.message)); } }

async function renderReports(){ const main=document.getElementById('main'); main.innerHTML=''; main.appendChild(el('h2',{},'Rapports')); try{ const stock = await call('getStock'); const sales = await call('getSales'); const totalStock = stock.reduce((a,r)=>a + Number(r.pu||0)*Number(r.stock||0),0); const caTotal = (sales||[]).reduce((a,s)=>a + Number(s.montant||0),0); const caLub = (sales||[]).filter(s=>s.type==='lub').reduce((a,s)=>a + Number(s.montant||0),0); main.appendChild(el('div',{class:'card'}, el('h4',{},'Valeur stock'), el('div',{}, formatCurrency(totalStock) ))); main.appendChild(el('div',{class:'card'}, el('h4',{},'CA total'), el('div',{}, formatCurrency(caTotal) ))); main.appendChild(el('div',{class:'card'}, el('h4',{},'CA lubrifiants'), el('div',{}, formatCurrency(caLub) ))); }catch(err){ main.appendChild(el('div',{},'Erreur: '+err.message)); } }

document.getElementById('btn-stock').addEventListener('click', renderStock);

document.getElementById('btn-sales').addEventListener('click', renderSales);

document.getElementById('btn-reports').addEventListener('click', renderReports);

renderStock();

